-- Pennywise runtime database schema
-- The backend connects to MySQL from `config/db.js`.
-- The source-of-truth DDL and seed data live in `../../database/expense_tracker.sql`.
-- This file intentionally stays as a pointer so the project does not keep two conflicting schemas.
